name: rsk1
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  persistent_bottom_nav_bar: ^5.0.2
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1
  image_picker: ^0.8.9
  easy_localization: ^3.0.2
  intl_phone_field: ^3.2.0
  pin_code_fields: ^8.0.1
  flutter_riverpod: ^2.3.6
  grock: ^0.3.3
  http: ^1.1.0
  shared_preferences: ^2.2.0
  dartz: ^0.10.1
  connectivity_checker: ^1.1.0
  flutter_secure_storage: ^8.0.0
  hooks_riverpod: ^2.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/translations/

